spring:
  flyway:
    url: jdbc:postgresql://database:5432/lpc
    user: postgres
    password: postgres
    schemas:
      - public
  datasource:
    url: jdbc:postgresql://database:5432/lpc
    username: postgres
    password: postgres