spring:
  profiles:
    active: ${APP_PROFILE:prod}
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5427/lpc
    user: postgres
    password: postgres
    baselineOnMigrate: true
    schemas:
      - public
  datasource:
    url: jdbc:postgresql://localhost:5427/lpc
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
security:
  googleClientId: 675787465559-lkdi5btt3t0e5nqta5sgkodq2k7scsgi.apps.googleusercontent.com
jwt:
  secret: isdohfiusdghfuidhfiusdhfiushdfuishdfushiudshfs7648f9h378f

file:
  upload-dir: uploads