spring:
  profiles:
    active: ${APP_PROFILE:prod}
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/lpc
    user: postgres
    password: postgres
    baselineOnMigrate: true
    schemas:
      - public
  datasource:
    url: jdbc:postgresql://localhost:5432/lpc
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
security:
  googleClientId: 25016646172-984m0a4h13fgpmlud14l5u89smit82f3.apps.googleusercontent.com
jwt:
  secret: isdohfiusdghfuidhfiusdhfiushdfuishdfushiudshfs7648f9h378f
